# Generated by Django 4.2.13 on 2024-12-29 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TransactionData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.IntegerField()),
                ("month", models.IntegerField()),
                ("year", models.IntegerField()),
                ("value_normalized", models.FloatField()),
                ("blockheight_normalized", models.FloatField()),
                ("from_encoded", models.CharField(max_length=255)),
                ("to_encoded", models.CharField(max_length=255)),
            ],
        ),
    ]
